// -------------------------------------------------------------
//
// File Name: hdlsrc\dac20_offset_calc.v
// Created: 2013-01-19 21:54:39
// Generated by MATLAB 7.6 and Simulink HDL Coder 1.3
//
//
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module dac20_offset_calc
          (
           InS32b,
           OutU20b
          );


  input   signed [31:0] InS32b;  // int32
  output  [19:0] OutU20b;  // ufix20


  wire signed [19:0] ToFix20bit_out1;  // sfix20
  wire signed [19:0] OFFSET_out1;  // sfix20
  wire [19:0] Sum2_out1;  // ufix20
  wire signed [20:0] Sum2_out1_tmp;  // sfix21
  wire signed [20:0] add_cast;  // sfix21
  wire signed [20:0] add_cast_1;  // sfix21
  wire signed [21:0] add_temp;  // sfix22

  assign ToFix20bit_out1 = ((InS32b[31] == 1'b0 & InS32b[30:19] != 12'b000000000000) || (InS32b[31] == 1'b0 && InS32b[19:0] == 20'b01111111111111111111) // special case0
) ? 20'b01111111111111111111 : 
      (InS32b[31] == 1'b1 && InS32b[30:19] != 12'b111111111111) ? 20'b10000000000000000000 : InS32b[19:0];

  assign OFFSET_out1 = 20'b01111111111111111111;

  assign add_cast = $signed({{1{ToFix20bit_out1[19]}}, ToFix20bit_out1});
  assign add_cast_1 = $signed({{1{OFFSET_out1[19]}}, OFFSET_out1});
  assign add_temp = add_cast + add_cast_1;
  assign Sum2_out1_tmp = (add_temp[21] == 1'b0 & add_temp[20] != 1'b0) ? 21'b011111111111111111111 : 
      (add_temp[21] == 1'b1 && add_temp[20] != 1'b1) ? 21'b100000000000000000000 : add_temp[20:0];

  assign Sum2_out1 = (Sum2_out1_tmp[20] == 1'b1 ) ? 20'b00000000000000000000 : $unsigned(Sum2_out1_tmp[19:0]);

  assign OutU20b = Sum2_out1;

endmodule  // dac20_offset_calc

