// -------------------------------------------------------------
//
// File Name: hdlsrc\mux24.v
// Created: 2013-05-30 00:05:14
// Generated by MATLAB 7.6 and Simulink HDL Coder 1.3
//
//
// -------------------------------------------------------------



`timescale 1 ns / 1 ns

module mux24
          (
           a1,
           sel,
           a2,
           a3,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           Mux_Data_o
          );


  input   [31:0] a1;  // uint32
  input   [4:0] sel;  // ufix5
  input   [31:0] a2;  // uint32
  input   [31:0] a3;  // uint32
  input   [31:0] a4;  // uint32
  input   [31:0] a5;  // uint32
  input   [31:0] a6;  // uint32
  input   [31:0] a7;  // uint32
  input   [31:0] a8;  // uint32
  input   [31:0] a9;  // uint32
  input   [31:0] a10;  // uint32
  input   [31:0] a11;  // uint32
  input   [31:0] a12;  // uint32
  input   [31:0] a13;  // uint32
  input   [31:0] a14;  // uint32
  input   [31:0] a15;  // uint32
  input   [31:0] a16;  // uint32
  input   [31:0] a17;  // uint32
  input   [31:0] a18;  // uint32
  input   [31:0] a19;  // uint32
  input   [31:0] a20;  // uint32
  input   [31:0] a21;  // uint32
  input   [31:0] a22;  // uint32
  input   [31:0] a23;  // uint32
  input   [31:0] a24;  // uint32
  output  [31:0] Mux_Data_o;  // uint32


  wire [31:0] Multiport_Switch_out1;  // uint32

  assign Multiport_Switch_out1 = (sel == 5'b00000) ? a1 :
                              (sel == 5'b00001) ? a2 :
                              (sel == 5'b00010) ? a3 :
                              (sel == 5'b00011) ? a4 :
                              (sel == 5'b00100) ? a5 :
                              (sel == 5'b00101) ? a6 :
                              (sel == 5'b00110) ? a7 :
                              (sel == 5'b00111) ? a8 :
                              (sel == 5'b01000) ? a9 :
                              (sel == 5'b01001) ? a10 :
                              (sel == 5'b01010) ? a11 :
                              (sel == 5'b01011) ? a12 :
                              (sel == 5'b01100) ? a13 :
                              (sel == 5'b01101) ? a14 :
                              (sel == 5'b01110) ? a15 :
                              (sel == 5'b01111) ? a16 :
                              (sel == 5'b10000) ? a17 :
                              (sel == 5'b10001) ? a18 :
                              (sel == 5'b10010) ? a19 :
                              (sel == 5'b10011) ? a20 :
                              (sel == 5'b10100) ? a21 :
                              (sel == 5'b10101) ? a22 :
                              (sel == 5'b10110) ? a23 :
                              a24;

  assign Mux_Data_o = Multiport_Switch_out1;

endmodule  // mux24

